apiVersion: v1
kind: Namespace
metadata:
  name: tenant1
  labels:
    name: tenant1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-deployment
  labels:
    app: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-app
          image:  local-registry:35543/example_app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: TENANT
              value: "tenant1"
---
apiVersion: v1
kind: Service
metadata:
  name: example-app
spec:
    selector:
        app: example-app
    ports:
        - port: 8080
          targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-app-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
    rules:
      - host: tenant1.k8s.local
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: example-app
                port:
                  number: 8080
