apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-01-deployment
  labels:
    app: service-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-01
  template:
    metadata:
      labels:
        app: service-01
    spec:
      containers:
        - name: service-01
          image: firstcluster-registry:41703/service_01:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-01
spec:
  type: ClusterIP
  selector:
    app: service-01
  ports:
    - port: 8080
      targetPort: 80