POST http://127.0.0.1:8000/api/instance
Content-Type: application/json

{
  "tenant_id": "1",
  "name": "Test Server",
  "slug": "test",
  "version": "0.1"
}

###
GET http://127.0.0.1:8000

###
DELETE http://127.0.0.1:8000/api/instance/1

### Update
PUT http://127.0.0.1:8000/api/instance/1
Content-Type: application/json

{
  "tenant_id": "1",
  "version": "0.2"
}
